Cart
alexcostaluiz/CSCI4050-Bookstore pull request #36
Opened 2020-11-20 03:05 UTC by lemonman96

2020-11-20 09:23 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/controller/EditController.java
> +          System.out.println(key.getIsbn());
Remove this?

2020-11-20 09:32 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/controller/UserController.java
> +        }
I think we should do this for suspend and unsuspend as well. When I suspend a user, if their already logged in, they can still use the site and even edit their profile information successfully, etc. I'd be great if we can invalidate them so that the most they can do is view public data, but they cant make any edit requests or anything like that. 

I can also add a check in the front end Authentication component, where if a user comes back with a suspended: true, I can automatically log them out and send them to the login page.

2020-11-20 09:34 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/model/Cart.java
> -public class Cart {
Why did you delete this file?

2020-11-20 09:38 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/controller/EditController.java
> +          System.out.println(key.getIsbn());
This is supposed to reference only line 201, the System.out.println

2020-11-20 09:38 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/model/User.java
> +  */
Did you mean to leave this commented out?

2020-11-20 09:39 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/model/User.java
> +  */
This is getOrders and setOrders in modal/User.java

2020-11-20 09:40 UTC, alexcostaluiz requested changes
looks great besides the couple comments above.

2020-11-20 17:42 UTC, lemonman96 commented on src/main/java/com/csci4050/bookstore/controller/UserController.java
> +        }
I'm gonna make a custom event to do it and add to sus and desus

2020-11-20 23:16 UTC, lemonman96 commented
delegated user expiration to an event, got rid of println's and comments. Also handled errors for when sending an email fails (connection error). We might want to add functionality to resend a confirmation or password reset token incase something like this happens. Also fixed the foreign key mapping in Order

2020-11-20 23:17 UTC, lemonman96 reviewed
Finished

2020-11-21 04:16 UTC, Marartu approved these changes

2020-11-21 17:51 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/model/User.java
> +      name = "book_quantity_mapping",
what if we named this cart or user_cart instead of this? I feel like that matches the whole order_cart thing better.

2020-11-21 17:52 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/model/User.java
> +      joinColumns = @JoinColumn(name = "cart_id", updatable = false, insertable = false))
Isn't this actually the user_id? Following the pattern of order_cart I feel like a better name for this column would be user_id, but idk if I'm assuming correctly about how this join column works.

2020-11-21 17:53 UTC, alexcostaluiz approved these changes
look great

2020-11-21 19:37 UTC, lemonman96 commented on src/main/java/com/csci4050/bookstore/model/User.java
> +      joinColumns = @JoinColumn(name = "cart_id", updatable = false, insertable = false))
my bad, i copied over the code from the cart class and neglected to update the names of the columns. fixing now

2020-11-21 20:13 UTC, merged