Tweaks
alexcostaluiz/CSCI4050-Bookstore pull request #37
Opened 2020-11-22 03:01 UTC by lemonman96

Fixing some random things and making things more clear

2020-11-22 11:38 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/model/Book.java
> +      List<Tag> tags) {
Do we need to add reviews to this constructor?

2020-11-22 11:38 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/model/Book.java
> +  public void setTags(List<Tag> tags) {
Do we need getter/setter for reviews?

2020-11-22 11:39 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/model/Review.java
> +  private Integer stars;
Lets make this a float so people can choose half-stars (1.5, 2.5, 3.5, 4.5 stars)

2020-11-22 11:39 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/model/Review.java
> +  private boolean reccomended;
recommended*

2020-11-22 11:40 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/model/Review.java
> +    this.reccomended = reccomended;
recommended*

2020-11-22 11:40 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/model/Review.java
> +  private boolean reccomended;
same for getter/setter below

2020-11-22 11:41 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/model/Tag.java
> +  BEST_SELLERS
Change to "BESTSELLER".

2020-11-22 12:00 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/model/Author.java
> +  private String role;
I think we should do this part a little differently.

I think like this we would end up with a lot of duplicated Authors in the database. My idea is lets move the role information into the `author_books` mapping table because the role is more of an attribute of the actual relationship between author and book and less so of an attribute of one author (one author may have different roles w/ different books (probably rare but definitely possible)). Then let's set the `name` column to be unique so that we don't accidently create any duplicate authors in the DB.

Then on the frontend side of things, I'll grab all the authors we have from a Author Controller endpoint and when someone is creating a book and typing in the author they can actually select the author from the dropdown. This way, if an existing author is selected, I will have its `id` information so when I send the JSON to the server for the book creation, a new author won't be created since I'm sending the id of the author. And if they enter in a name that does not match anything that I've pulled from the DB, I will end up sending an author without `id` information, in which case the backend will know to create a new author in the DB. 

And every time a book is created we definitely have to create at least one row in this author_books table so we'd just have to figure out how to send the role information correctly to this author_books table, not sure if Spring will automatically know to do that, but I'm sure there's an easy way to send extra data to the JoinTable.

Let me know what you think of this design.

2020-11-22 12:01 UTC, alexcostaluiz requested changes
These changes are awesome. Are you planning on creating controllers for these new classes (Author, Review, Tag)? I'd probably need endpoints for Create/Retrieve/Update/Delete for each.

2020-11-22 12:26 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/model/Review.java
> +  private Integer stars;
We should also add a check in setStars that makes sure that `value % 0.5 == 0`.

2020-11-23 16:24 UTC, lemonman96 commented on src/main/java/com/csci4050/bookstore/model/Book.java
> +      List<Tag> tags) {
I'm gonna actually get rid of the constructor, it's the only class that has one. I only use it for booktest

2020-11-23 16:25 UTC, lemonman96 commented on src/main/java/com/csci4050/bookstore/model/Book.java
> +  public void setTags(List<Tag> tags) {
I haven't implemented review logic yet, these are just placeholders for now.

2020-11-24 14:25 UTC, lemonman96 commented on src/main/java/com/csci4050/bookstore/model/Author.java
> +  private String role;
So spring is already making a join table using that many-many relationship annotation. I instead made a custom one that holds the author, book and role information.

2020-11-28 20:21 UTC, closed without merging