Checkout
alexcostaluiz/CSCI4050-Bookstore pull request #38
Opened 2020-11-22 03:03 UTC by lemonman96

finished checkout and order history

2020-11-22 12:06 UTC, alexcostaluiz commented
Changing the base to `tweaks` since this branch was branched off tweaks (includes all of tweaks commits).

2020-11-22 12:09 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/controller/EditController.java
> +          user.setCart(null);
Should we just set this to an empty list? Seems safer than null.

2020-11-22 12:13 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/dao/OrderDAO.java
> +    Query<Order> query = session.createQuery("FROM card", Order.class);
"FROM card"? Should be "FROM order" right?

2020-11-22 12:14 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/dao/UserDAO.java
> +    return id;
Collapse these 2 lines into 1 line?

2020-11-22 12:14 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/dao/VerificationTokenDAO.java
> +  }
Are we purposely doing nothing in this method?

2020-11-22 12:16 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/dto/CartDto.java
> +package com.csci4050.bookstore.dto;
This file is CartDto and then later there is OrderDTO, we should standardize whether DTO is in all caps or not.

2020-11-22 12:17 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/dto/CartDto.java
> +package com.csci4050.bookstore.dto;
Since DAO is all caps, I think we should change any lowercase Dto's -> DTO.

2020-11-22 12:17 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/dto/PasswordDto.java
> +package com.csci4050.bookstore.dto;
Capitalize DTO (or Change OrderDTO to OrderDto).

2020-11-22 12:18 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/dto/PasswordDto.java
>  public class PasswordDto {
Capitalize DTO (or Change OrderDTO to OrderDto).

2020-11-22 12:21 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/model/Order.java
I actually think using LocalDateTime would be better here than just a LocalDate. I don't see why we'd want to throw away the time information.

2020-11-22 12:21 UTC, alexcostaluiz commented on src/main/java/com/csci4050/bookstore/dto/OrderDTO.java
> +  private LocalDate orderDate;
Not sure if the other comment relating to this is above or below, but I think we should keep the time information, so using a LocalDateTime would be better, unless there is a specific reason I'm missing.

2020-11-22 12:24 UTC, alexcostaluiz requested changes
looks good, a couple changes requested.

2020-11-23 17:31 UTC, lemonman96 commented on src/main/java/com/csci4050/bookstore/dto/PasswordDto.java
>  public class PasswordDto {
Did you want to change the format of DAO? I just matched how we've been naming our dao's

2020-11-23 17:32 UTC, lemonman96 commented on src/main/java/com/csci4050/bookstore/dao/VerificationTokenDAO.java
> +  }
I set it to do nothing since we shouldn't update a token after it's been created. But i can add some logic and restrict in the service layer

2020-11-23 17:49 UTC, lemonman96 commented on src/main/java/com/csci4050/bookstore/controller/EditController.java
> +          user.setCart(null);
I now have the user class instantiating an empty mapping by default and clearing that map when checking out

2020-11-28 20:22 UTC, lemonman96 commented
changes requested from tweaks are pushed here

2020-11-28 20:33 UTC, merged